#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ansi
Version  : 1.5.0
Release  : 6
URL      : https://rubygems.org/downloads/ansi-1.5.0.gem
Source0  : https://rubygems.org/downloads/ansi-1.5.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
BuildRequires : ruby
BuildRequires : rubygem-ae
BuildRequires : rubygem-ansi
BuildRequires : rubygem-ergo
BuildRequires : rubygem-indexer
BuildRequires : rubygem-lemon
BuildRequires : rubygem-mast
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubytest
BuildRequires : rubygem-rubytest-cli

%description
# ANSI
[HOME](http://rubyworks.github.com/ansi) &middot;
[API](http://rubydoc.info/gems/ansi/frames) &middot;
[MAIL](http://googlegroups.com/group/rubyworks-mailinglist)  &middot;
[ISSUES](http://github.com/rubyworks/ansi/issues) &middot;
[SOURCE](http://github.com/rubyworks/ansi)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ansi-1.5.0
gem spec %{SOURCE0} -l --ruby > rubygem-ansi.gemspec

%build
gem build rubygem-ansi.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ansi-1.5.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ansi-1.5.0 && rubytest -I.:lib:test test/case_*.rb && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ansi-1.5.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/ansi-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/ansi_to_bbcode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/ansi_to_html-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/bbcode_to_ansi-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/bbcode_to_html-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/cdesc-BBCode.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/html_to_ansi-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/html_to_bbcode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/BBCode/strip_bbcode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Chain/cdesc-Chain.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Chain/codes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Chain/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Chain/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Chain/string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Chain/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Chain/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/ansi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/back-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/cdesc-Code.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/colors-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/display-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/down-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/forward-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/hex_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/left-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/move-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/random-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/rgb-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/rgb_256-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/rgb_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/right-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/styles-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/unansi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/uncolor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/unstyle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Code/up-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/align%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/align-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/ansi_formatting-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/cdesc-Columns.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/columns%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/format%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/join-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/list%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/padding%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/padding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Columns/to_s_columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Constants/cdesc-Constants.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/cdesc-Diff.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/common-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/compare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/diff-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/diff1-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/diff2-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/diff_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/join-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/lcs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/lcs_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Diff/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/cdesc-HexDump.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/dump_random-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/index%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/HexDump/template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/ansicolor%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/ansicolor%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/cdesc-Logger.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/debug_with_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/error_with_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/fatal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/fatal_with_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/formatter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/info_with_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/styles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Logger/warn_with_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black_on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black_on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black_on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black_on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black_on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black_on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/black_on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blink-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue_on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue_on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue_on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue_on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue_on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue_on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/blue_on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/bold-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cdesc-Mixin.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/concealed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan_on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan_on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan_on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan_on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan_on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan_on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/cyan_on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/dark-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/display-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green_on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green_on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green_on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green_on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green_on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green_on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/green_on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/italic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta_on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta_on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta_on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta_on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta_on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta_on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/magenta_on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/negative-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/rapid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red_on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red_on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red_on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red_on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red_on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red_on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/red_on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/reverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/strike-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/underline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/underscore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white_on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white_on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white_on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white_on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white_on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white_on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/white_on_yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow_on_black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow_on_blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow_on_cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow_on_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow_on_magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow_on_red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Mixin/yellow_on_white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/bar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/bar_mark%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/barmark%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/bytes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/cdesc-ProgressBar.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/colorize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/convert_bytes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/elapsed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/eol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/eta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/file_transfer_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/flush-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/format_arguments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/format_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/get_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/halt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/inc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/mark%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/percentage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/show-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/show_progress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/standard_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/stat-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/stat_for_file_transfer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/styles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/title%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/total_overflow%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/transfer_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/ProgressBar/transfer_rate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/%2b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/ansi%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/ansi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/black%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/blue%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/bold%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/bold-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/color%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/cyan%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/downcase%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/downcase-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/green%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/gsub%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/gsub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/magenta%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/marks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/red%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/shift_marks%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/shift_marks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/slice-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/sub%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/sub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/underline%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/underline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/upcase%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/upcase-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/yellow%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/String/yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/align-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/ansi_formating-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/apply_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/border-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/cdesc-Table.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/cell_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/column_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/dividing_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/fit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/fit_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/max_columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/padding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Table/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/GetConsoleMode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/GetConsoleScreenBufferInfo-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/GetStdHandle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/SetConsoleEcho-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/SetConsoleMode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/cdesc-Terminal.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/get_character-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/raw_no_echo_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/restore_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/screen_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/terminal_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/terminal_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/Terminal/terminal_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/cdesc-ANSI.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/metadata-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/ANSI/string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/Logger/LogDevice/cdesc-LogDevice.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/Logger/cdesc-Logger.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/Object/ansi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/String/ansi%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/String/ansi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/String/unansi%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/String/unansi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/page-DEMO_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/page-NOTICE_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/ansi-1.5.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/.index
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/DEMO.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/NOTICE.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/01_ansicode.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/02_core.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/03_logger.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/04_progressbar.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/05_mixin.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/06_string.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/07_columns.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/08_table.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/09_diff.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/10_bbcode.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/11_terminal.md
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/applique/ae.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/demo/applique/output.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi.yml
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/bbcode.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/chain.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/chart.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/code.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/columns.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/constants.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/core.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/diff.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/hexdump.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/mixin.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/progressbar.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/string.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/table.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/terminal.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/terminal/curses.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/terminal/stty.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/terminal/termios.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/terminal/win32.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/lib/ansi/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/test/case_ansicode.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/test/case_bbcode.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/test/case_mixin.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/test/case_progressbar.rb
/usr/lib64/ruby/gems/2.2.0/gems/ansi-1.5.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/ansi-1.5.0.gemspec
